on:
  push:
    branches:
      - src

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website src
        uses: actions/checkout@v2

      - name: Checkout stgit repo
        uses: actions/checkout@v2
        with:
          repository: stacked-git/stgit
          fetch-depth: 0
          path: stgit

      - name: Fetch stgit tags
        run: |
          cd stgit
          git fetch --prune origin +refs/tags/*:refs/tags/*

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache Python dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Install other dependencies
        run: |
          sudo apt-get update
          sudo apt-get install asciidoc

      - name: Build Site
        run: |
          make STGIT_WORKTREE=stgit build

      - name: Deploy to master
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: master
